// flow-typed signature: 6e769b655d85f4b9d7f1bffd7c8eec28
// flow-typed version: <<STUB>>/apollo-fetch-upload_v^1.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-fetch-upload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-fetch-upload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-fetch-upload/dist/main/index' {
  declare module.exports: any;
}

declare module 'apollo-fetch-upload/dist/module/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-fetch-upload/dist/main/index.js' {
  declare module.exports: $Exports<'apollo-fetch-upload/dist/main/index'>;
}
declare module 'apollo-fetch-upload/dist/module/index.js' {
  declare module.exports: $Exports<'apollo-fetch-upload/dist/module/index'>;
}
