// flow-typed signature: 2bdf7a9301ec7d778cce6612819fc849
// flow-typed version: <<STUB>>/apollo-link-ws_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-ws/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/lib/webSocketLink' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-ws/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-ws/lib/bundle.umd'>;
}
declare module 'apollo-link-ws/lib/webSocketLink.js' {
  declare module.exports: $Exports<'apollo-link-ws/lib/webSocketLink'>;
}
declare module 'apollo-link-ws/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-ws/rollup.config'>;
}
