// flow-typed signature: 6e34e788214f8c8fbb878cc73da182ab
// flow-typed version: <<STUB>>/graphql-auth_v^0.2.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-auth/build/index' {
  declare module.exports: any;
}

declare module 'graphql-auth/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-auth/build/index.js' {
  declare module.exports: $Exports<'graphql-auth/build/index'>;
}
declare module 'graphql-auth/index' {
  declare module.exports: $Exports<'graphql-auth'>;
}
declare module 'graphql-auth/index.js' {
  declare module.exports: $Exports<'graphql-auth'>;
}
declare module 'graphql-auth/test.js' {
  declare module.exports: $Exports<'graphql-auth/test'>;
}
